[project]
name = "memlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataclasses>=0.8",
    "langchain-google-genai>=4.3.2",
    "langchain-groq>=1.1.3",
    "uuid>=1.30",
    "python-dotenv"
]

[dependency-groups]
test = [
    "langchain-chroma",
    "langchain-huggingface",
    "sentence-transformers",
]

[tool.uv]
add-bounds = "exact"
exclude-newer = "7 days"